language: objective-c
os: osx
osx_image: xcode7.3

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

cache:
  - bundler

before_script:
  - carthage bootstrap

script:
  - bin/fastlane test

after_success:
  - bash <(curl -s https://codecov.io/bash)
